### ISSUE TITLE
ChromeDriver only support Chrome version 121

### ISSUE THREAD

**Issue by SgtSobieski** [LtCMDstone/MS-Rewards-Farmer-Docker#4]
Hi,

its my first time to set up a docker container and I was pretty proud to get that far to that error message. I just wanted to ask, if the repository isnt up to date with the latest chrome version 121 or if i messed something up...

Thanks in advance!

**Comment by LtCMDstone** [comment]
I've just built two new versions, with chrome 121 and chrome 122 (latest)
