### ISSUE TITLE
Chrome version

### ISSUE THREAD

**Issue by schumijo** [LtCMDstone/MS-Rewards-Farmer-Docker#8]
Hi @LtCMDstone 

Thank you for your work
Can you update your image to Chrome 125 ?

from session not created: This version of ChromeDriver only supports Chrome version 125
Current browser version is 124.0.6367.118

**Comment by LtCMDstone** [comment]
Hey, it's done now 😄 
Need to find a automatic trigger for it 😃

**Comment by schumijo** [comment]
Thanks you now I am stick with 2FA as mentionned in issue #7
